# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image:
  name: 307489639749.dkr.ecr.ap-south-1.amazonaws.com/moneytor-build:nodev12
  aws:
    access-key: $AWS_ACCESS_KEY_ID
    secret-key: $AWS_SECRET_ACCESS_KEY

options:
  max-time: 15  # Time in minutes after which a build will timeout
  size: 2x # Double resources available for this step.

pipelines:
  custom:   # These builds will only be triggered manually
    Deploy-moneytor.in:
     - step:
        name: Build and deploy
        script:
          - $BITBUCKET_CLONE_DIR/devops-scripts/deploy.sh